#!/bin/bash
set -e

# This script can be used to export an asciidoc directory into a HTML or PDF zip bundle.
# Required : a running docker installation
# It is not intented to be full featured, feel free to adapt it to your needs

# [--pdf] to create a PDF + HTML bundle
# [--adoc] to create a source bundle with only the .adoc files
# [--html] to create an HTML-only bundle with embedded images

OUT=/tmp/architecture-document
ARCHIVE=/tmp/architecture-document-$(date +%y%m%d).zip
rm -rf $OUT > /dev/null 2>&1 || true 
mkdir $OUT
rm $ARCHIVE > /dev/null 2>&1 || true 
cp -rp *.adoc diagrams $OUT/

cd $OUT
for doc in $(find . -name '*.adoc' -print);  do
  if [[ $1 =~ '--adoc' ]]; then
    continue
  fi
  # -a option allow offline reading (embedded images into HTML files)
  docker run --rm -v $OUT:/data asciidoctor/docker-asciidoctor asciidoctor -a data-uri -a allow-uri-read -b html5 /data/$doc
  doc_without_extension=${doc%.adoc}
  if [[ $1 =~ '--pdf' ]]; then
     docker run --rm -v $OUT:/data madnight/docker-alpine-wkhtmltopdf --footer-center [page]/[topage] /data/$doc_without_extension.html /data/$doc_without_extension.pdf
  fi
done

# Fix links among documents
find . -name '*.html' -exec sed -i 's/.adoc/.html/g' {} \;

if [[ $1 =~ '--html' ]]; then
    find . -name '*.adoc' -exec rm {} \;
    rm -rf .git > /dev/null 2>&1 || true   
fi

# Final archive creation
cd /tmp
zip -r $ARCHIVE $(basename $OUT)
echo "Archive successfully produced in $ARCHIVE"