author: Bertrand Florat
license: CC BY-SA 4.0
views:
  - name: Application
    file: view-application.adoc
  - name: Development
    file: view-development.adoc
  - name: infrastructure
    file: view-infrastructure.adoc
  - name: Security
    file: security.adoc
  - name: sizing
    file: view-sizing.adoc
