author: Bertrand Florat
license: CC BY-SA 4.0
views:
  - name: Application
    file: view-application.adoc
  - name: Development
    file: view-development.adoc
  - name: infrastructure
    file: view-infrastructure.adoc
  - name: Security
    file: view-security.adoc
  - name: sizing
    file: view-sizing.adoc
labels:
  - name: level
    available_values:
      - basic
      - intermediate
      - advanced
  - name: project_size
    available_values: 
      - small
      - medium
      - large
  - name: project_size
  - detail_level: 
      - abstract      # conceptual, principles, big picture
      - overview      # broad but slightly more concrete
      - detailed      # technical specifics, diagrams, modules
      - in-depth      # exhaustive detail, e.g., data models, algorithms
  - name: persistence
  - name: green-IT
  - name: open-questions
  - name: context
  - name: constraint
  - name : solution
  - name: requirement
  