= Development component
:sectnumlevels: 4
:toclevels: 4
:sectnums: 4
:toc: left
:icons: font
:toc-title: Summary

Last modified: {docdate}

== Introduction

This is the development point of view of the application. It describes the code to be produced and how to write it.

The other parts of the file are accessible at link:./README.adoc[from here].

The project glossary is available at link:glossaire.adoc[here]. We will not redefine the functional or technical terms used here.

IMPORTANT: *This a WIP English translation of https://github.com/bflorat/modele-da[this project]. Suggestions and help appreciated.*


=== Reference Documentation

[TIP]
Mention here the reference architecture documents (shared). This document must in no case include their content, otherwise it will quickly become obsolete and unmaintainable.

. Development documentary references
[cols="1e, 1e, 4e, 4e"]
|====
| N ° | Version | Document title / URL | Detail

| 1 | 1.0 | https: //references.modernisation.gouv.fr/rgaa-accessibilite/#menu
| RGAA

|====

== Not ruled

=== Points subject to further study

Points subject to further study
[cols="e, e, e, e, e"]
|====
| ID | Detail | Status | Subject holder | Deadline

| ED1
| The choice of Angular or React.JS for the frontend is still under study. This does not impact the back part of REST services
| IN_CURRENT
| Methods and tools team
| BEFORE 2040

|====


=== Assumptions

.Hypotheses
[cols="1e, 4e"]
|====
| ID | Detail

| HD1
| Even if this point is not yet fully validated, the application will require a JRE 9 + to take advantage of the Java libraries and frameworks essential to the project.
|====

== Constraints

=== Network constraints
=== Network constraints
[TIP]
====
List here the constraints relating to the software architecture, this includes for example but not only:

* The obligation to use a framework or a specific technological sector
* Maximum license or development budgets
* Tooling (IDE, ...)
* Continuous integration
* The applicable code quality standards and thresholds
* Tests (coverage rate, breakdown by type of test, etc.)

====
====
Example 1: Code coverage should be at least 60%
====
====
Example 2: The module should be based on the Hibernate framework for persistence and CDI for dependency injection
====
====
Example 3: the application will be built, tested and deployed continuously with each push via the Gitlab platform
====

== Non-functional requirements

[TIP]
====
Contrary to the constraints which fixed the framework to which any application had to conform, the non-functional requirements are given by the project leaders (MOA in general). Schedule interviews to determine them. If certain requirements are not realistic, mention this in the reference points to be decided.
====

=== Accessibility

[TIP]
====
Should this application be accessible to the blind / visually impaired? hard of hearing?

If so, what level of accessibility?
Preferably refer to the General Accessibility Repository (https://references.modernisation.gouv.fr/rgaa-accessibilite/#menu→RGAA]) which recommends a WCAG 2.0 AA level:

There are other accessibility standards (WCAG, AccessiWeb…). Be careful to correctly assess the target level (neither over-quality nor under-quality):

* Achieving a very high level of accessibility can be costly and technologically demanding. It also requires good skills (accessibility, HTML5 / CSS3 in particular) and rare profiles.
* The law is increasingly strict for administrations which must respect a sufficient level of accessibility (law n ° 2005-102 of February 11, 2005 for equal rights and opportunities, participation and citizenship of people with disabilities ). "All European public sites must achieve the double A (AA) of W3C / WAI".
====

=== Ergonomics

==== Ergonomic charter

[TIP]
====
In general, we refer here to the body's ergonomic charter. List any specificities, however. Do not use the accessibility constraints listed above.
====
 
==== Specificities on widgets

[TIP]
====
Very precise ergonomic behavior can have a fairly strong impact on the architecture and impose a library of graphic components or another. It is strongly advised not to customize existing libraries (very high maintenance cost, great complexity). Choosing the right bookstore or restricting your needs.
====
====
Example 1: the tables must be sortable according to several columns.
====
====
Example 2: many screens will be fitted with accordions
====

==== Fonts

[TIP]
====
Describe here the fonts to use for web pages, applications, or compound documents.

The choice of fonts follows licensing constraints. In order to ensure legal security for the project, pay attention to commercial policies subject to royalties (in particular policies apartment to Microsoft such as Times New Roman, Courier, Verdana, Arial) and which do not allow free production.documents without going through their editors (Word, ...).

See, for example, the police https://www.gouvernement.fr/charte/charte-graphique-les-fondamentaux/la-typographie postaleMarianne] recommended by the government as a variable-range police.

Redhat offers four families of fonts https://fr.wikipedia.org/wiki/Liberation_(police_d%27%C3%A9criture)(Liberation Mono] under an Open Source license that is legally secure and compatible with the Monotype, the Mail New, Arial and Times New Roman.
====

==== Responsive website

[TIP]
====
List the multi-media display constraints. When possible, use modern frameworks (such as AngularJS or React.js). There are several levels of adaptation of web pages:

* Static (fixed page width).
* Dynamic (automatic resizing, sizes are expressed in%).
* Adaptive (distances are expressed in units, the size of which depends on the support).
* Responsive (the content and its layout depend on the medium).

Attention, a responsive design comes with its constraints (code duplication, increase in the volume of the site to be downloaded by the customer, complexity, no more end-to-end tests to be expected…).
====

==== Progressive Web Apps (PWA)

[TIP]
====
Specify whether the application is progressive. PWA applications are HTML5 web applications having all the attributes of native applications (offline, fast, adaptive, accessible from the OS, ...)
====
====
Example: Application X will be totally PWA. Tests will have to demonstrate that the site will continue to operate without a network and that the pages load in less than 5 seconds in 4G.
====

==== Supported browsers

[TIP]
====
Specify which browsers are supported if it is a Web GUI.

When addressing an audience whose fleet of browsers you do not manage (such as a website on the Internet), the best option to make things intelligible and clarify the issues is to negotiate with the stakeholders of the project a percentage audience supported based on https://gs.statcounter.com/ouvernstatistics]. For example: "Support 95% of browsers".

Warning: supporting old browsers (IE in particular) can generate prohibitive additional costs (except when using a library that masks this complexity and hoping that it works correctly).

In all cases, the additional costs of testing on multiple platforms should be assessed. There are good (paid) tools like Litmus or EmailOnAcid to render websites and HTML emails on a combination of OS / player type (PC / tablet / mobile) / browser very large (in the order of of 50).

This type of site is essential for a general public application.
====
====
Example 1: The intranet application X must work on internally qualified browsers (see xyz standard)
====
====
Example 2: Application Y being an internet application targeting the widest possible audience, including terminals in developing countries. It will have to support Firefox 3+, IE 8+, Opera 6+.
====
====
Example 3: Application Z is aimed at the broadest audience and with reasonably old systems and will therefore have to support: Firefox 6+, Chrome 8+, Opera 8+, IE 10, Edge.
====

==== Internationalization (i18n)

[TIP]
====
Specify the constraints of the application in terms of i18n: location of labels, direction of the text, adaptable layout, specific color code, date format, currencies, display of decimal separators, etc.
====
====
Example 1: The GUI X will be translated into 25 languages ​​including some Asian languages ​​and Arabic.
====
====
Example 2: Date formats and other input fields must be perfectly localized for maximum user convenience.
====

==== Offline mode

[TIP]
====
Specify whether the application must be able to continue to function without Internet or LAN access (very common for applications used by professionals on the move for example).

These can be classic heavy clients (Java, C, ...) having their local database that can be synchronized back to the office. They can also be PWA applications (see above) using a service worker for static resources and browser storage (local storage, IndexedDB HTML5 base).
====
====
Example 1: The application will be developed in Java Swing with local storage based on an H2 database synchronized with the common database by REST calls.
====
====
Example 2: The mobile application will be in PWA mode, entirely written in HTML5 with local storage to store the day's data in the browser.
====

=== SEO Requirements

[TIP]
====
SEO (Search engine optimization) concerns the visibility of a website through search engines (like Google or Quant).
====
====
Example 1: No indexing necessary or desired (internal site)
====
====
Example 2: The static pages of the site must follow good SEO practices to optimize its visibility.
====

== Target architecture

=== Software stack

==== Technical stream selected

[TIP]
====
Donate the technologies chosen from the technologies in the organization's catalog. If there are any discrepancies with the catalog, specify and justify it.
====
====
Example: this application has profile P3: "Spring Web Application" with exceptional use of the JasperReport library.
====
====
Example: Using Reacts.js on an experimental basis within the organization. Validated in architecture committee on ...
====

==== Software components

[TIP]
====
List here for each component the main libraries and frameworks used as well as their version. Do not list the libraries supplied to the runtime by the application servers or the frameworks. No need to go into too much detail, give only the structuring components.
====
====
Example:

Software stack example
[cols="1e, 4e, 1e"]
|====
| Library | Role | Version

| Angular2 Framework
| Presentation JS Framework
| 2.1.1

| JasperReport
| Transactional editing, composition of invoices in PDF format
| 6.3.0
|====
====

=== Performance

IMPORTANT: See the MOA requirements in the link:./component-architecture-sizing.adoc[Sizing section].


[TIP]
====
Even though performance campaigns are planned and performance analyzes will be integrated into the CI / CD, experience shows that 50% of performance problems could have been detected during development.
It is therefore important that developers profile their code from their workstation (to be provided in the Definition Of Done of the project). It will not be possible to detect all the problems (scalability, concurrency, robustness, cache tuning, ...) but most of the response time problems. We present here some very basic ideas and accessible to any developer.


Frontend side:

* Limit the complexity of CSS (selectors or functions in particular)
* Use a profiler (like the one in Chrome)
* Favor asynchronous calls
* ...

Backend side:

* Make sure that the server paging goes up to the database (`LIMIT`,` OFFSET`).
* Do not put in place unnecessary constraints in the database.
* Limit the number of joins and many-to-many relationships.
* In cases of large volumes, study the solutions for partitioning tables.
* Don't forget to add all the necessary indexes, use the analysis of the execution plan to verify that there are no full scans.
* Beware of SQL functions that 'break' indexes (like `UPPER ()`). Give priority to processing on the backend code side if possible.
* Activate the query logs (Hibernate example: `org.hibernate.SQL = DEBUG`,` -Dhibernate.generate_statistics = true`) and check the SQL queries and their number (to detect in particular the problem of https: // stackoverflow .com / questions / 97197 / what-is-the-n1-selects-problem-in-orm-object-relational-mapping[SELECT N + 1], very common).
* Have a minimum data set (around a hundred records) even on a workstation.
* Check with a profiler (like JVisualVM in Java) the memory consumption to detect leaks or overconsumption.
* Check that there are no threads or deadlock leaks by counting the number of active threads.
* Stress the API _a minima_ (with injectors like Jmeter or K6) and via a progressive ramp.
* Track IOs (millions of times slower than memory accesses).
* ...

Frontend and backend:

* Any resource (chain size, number of calls over a period, ...) must always be limited by a limit (no open bar).
* Check that the size of HTTP requests remains below a few tens of KiB (excluding GET on files). Use "Sorting and Pagination, client and server pagination".
* Track network chatter: group requests when possible (you have to find a compromise with the previous rule). Use the SOLID (Segregation Interface) rule 'S'.
* Provide multivalued endpoints (example: `GET / people? List = id1, id2, ...`) to retrieve several elements at the same time
(must result in a single `SELECT WHERE .. IN` in the final query, not a loop in the code!)

====

WARNING: Do not fall back into premature optimization "the source of all the problems" according to Donald Knuth. Write the simplest code possible and follow a good design, only optimize it afterwards.
Only optimize if it is worth the cost (Pareto law). Start with the most significant optimizations and do not waste time grabbing microseconds or even nanoseconds.


=== Software factory specifics

[TIP]
====
Without resuming the functioning of the organization's PIC (Continuous Integration Platform), specify whether this project requires a particular configuration.
====
====
Examplee: Jenkins jobs will produce the software as Docker containers if all TUs are on. The integration tests will then be run on this container. If all integration and BDD tests pass, the Docker image is released into Nexus.
====

=== Development standards and qualimetry

[TIP]
====
Make explicit the rules and the level of quality required for the code
====
====
Example 1: The quality rules to be used for the code will be (https://rules.sonarsource.com/javaogène standard SonarQube for Java rules]).
====
====
Example 2: The required quality level corresponds to the recommended https://docs.sonarqube.org/6.7/QualityGates.html[Quality Gate SonarQube]:

* 80% minimum code coverage
* 3% max of duplicate lines
* Level A in Maintenabily, Relability and Security
====

====
Example 3: What language used for the code? French for functional terms (it is imperative to use business terms as recommended by the DDD) and English for generic technical terms.
====

=== Notable patterns

[TIP]
====
Specify whether this project has implemented structuring patterns (GoF, JEE or other). No need to use patterns already supported by languages ​​or application servers (for example, IoC with CDI in a JEE 6 server).
====
====
Example 1: to deal with the combinatorial explosion of possible contracts and avoid multiplying the levels of inheritance, we will massively use the decorator pattern[GoF], of which here is an example of use: <diagram>.
====

=== Specificities of the tests

[TIP]
====
Is there a particular methodology or technology involved in this project? What is the testing strategy?
====
====
Example 1: this project will be covered in addition to the TUs and integration tests because BDD (Behavioral Driven Development) acceptance tests in JBehave + Serenity technology.
====
====
Example 2: this project will be developed in TDD (test first)
====
====

Example 3: Types of tests

Types of tests
[cols = '2s, 1,1,1,1,4a']
|====
| Type of test | Time to invest | Manual or automated? | Type of module targeted | Target Coverage Rate | Detail

| TU
| Very high
| Automated
| Backend and Frontend
| approx. 80%
| BDD format: behavior specifications for classes and methods

| Executable specifications
| Very high
| Automated
| API
| approx. 100% for the domain classes
| Corked mode.

| Contract tests
| Low
| Automated
| UI / API links
| approx. 100% of the calling code on the UI side and Spring controllers on the API side
| Tests non-regression of exchanges when calling REST API operations (CDC = Consumer-Driven Contract principle) via the Pact and pact-react-consumer tools.

| Architecture tests
| Very low
| Automated
| API and batches
| N / A, 100% of the code is validated by the tool
| In particular, these easy-to-write tests will verify compliance with the rules of the hexagonal architecture. Use of the ArchUnit test framework.

| TI (integration tests)
| Low
| Automated
| Components calling external systems (databases, API ...)
| 50 to 60%
| Each IT should only test one external system at a time

| E2E (end-to-end testing)
| Low
| Automated
| UI
| 30%, nominal cases (happy path)
| Written in CodeceptJS, Selenium or similar technology. They will be limited to a role of smoke tests (detection of gross problems). These tests will not be corked but will be carried out on an end-to-end instantiated link chain. To avoid unnecessary work, these tests will be done at the level of entire features, not necessarily at each sprint. These tests will also serve as system tests since they will require a maximum of uncapped modules.

| Performance tests
| Low (excluding dedicated performance campaigns)
| Automated
| Critical APIs
| 20%
| Possibly automated in CI in DEV but also manually launched by the developers

| Accessibility tests
| Average
| Automated + manual
| UI
| 50%
| Ax-Core tests launched in CI to complete with a manual audit

| Security tests
| Average
| Manual
| All
| Low, only on sensitive functions
| Audit to be scheduled

| System tests
| Low
| Manuals
| UI and batches
| 10%
| Tests carried out by the development team covering full functional scenarios. The goal
is here to test the operation of all the modules (which cannot be automated) and to
detect as many bugs as possible before UAT tests.

| UAT (acceptance) tests
| Average
| Manuals
| UI, hand-launched batches
| from 30% to 80% depending on the number of scenarios planned
| Tests carried out in acceptance by the MOA on an uncapped environment with test books. End-to-end acceptance tests (we follow a test booklet with nominal cases), Exploratory tests (we try all possible combinations with minimal guidance in the test booklet)
|====
====

NOTE: For a large projecture, the test strategy is usually the subject of a separate document. A standard strategy can also be defined at the IS level.

=== Eco-design

[TIP]
====
List here the software measures to meet the ecodesign requirements listed in the infrastructure section. The answers to its problems are often the same as those to the performance requirements (response time in particular). In this case, just refer to it. However, ecodesign analyzes and solutions can be specific to this theme.
Some avenues for energy improvement of the project:

* Use profilers or development tools integrated in browsers (like Google Dev Tools) to analyze the consumption of resources (number, duration and size of requests).
* For apps, use battery consumption monitoring tools like Battery Historian.
* Use the specialized Greenspector analysis suite.
* Measure the power consumption of systems with PowerAPI2 probes (developed by INRIA and Lille 1 University).
* Measure the size of images and reduce them (lossless) with tools like pngcrush, OptiPNG, pngrewrite or ImageMagick.
* Optimize memory and CPU consumption of applications, tuner GC for a Java application.
* Lazy loading for occasional resource loading.
* Limit the results returned from the database (select) to the HTML pages returned via the data on the server side.
* Group the mass treatments in batches which will be more efficient (batches).
====
====
Example 1: The gulp application building process will apply an image size reduction via the imagemin-pngcrush plugin.
====
====
Example 2: robustness tests running over several days will be performed on the mobile application after each optimization to assess the energy consumption of the application.
====
====
Example 3: The performance campaigns will integrate a detailed analysis of the consumption of bandwidth and CPU cycles even if the response time requirements are covered, this to identify optimizations allowing to meet the eco-design requirements if they do not. are not achieved.
====

=== Management of robustness

==== Transaction management

[TIP]
====
List here the decisions taken regarding the management of transactions. This is especially useful for a distributed system. Some examples of issues:

* Are updates allowed on multiple components during the same request?
* If so, do we ensure the ACID character at all (via XA mode for example)?
* What transactional engine do we use?
* What level of transactional isolation (read commited, uncommited, repeatable read, serializable)?
* If no transactional monitor is used (call of several REST services in update for example), are there any compensatory transactions in the event of failure of one of the updates?

====
====
Example: our resources are not transactional (REST services), and wanting to avoid making compensatory transactions, it is forbidden to call two update services synchronously. If necessary, we will use a queue to make updates as needed.
====

==== Session management

[TIP]
====
How are HTTP sessions managed to provide an execution context to a user (example: their shopping cart)?

Note that this is primarily a problem for classic web applications whose presentation is generated on the server, not for Single Page Application (SPA) applications which manage all presentation and state locally in the browser.

The choices made here will affect the links: component-architecture-infrastructure[choice of infrastructure]. For example, if a session is required and the infrastructure is clustered, it will either be necessary to set up session affinity on the servers to force each user to always arrive on the same server with their data, or to set up a distributed cache allowing servers to share sessions for all users (more complex).

Examples of points to be addressed:

* What data should be kept in session? (pay attention to the volume, especially if the cache is distributed)
* Should the code be thread-safe (if the same user opens another tab in his browser for example)?

====
====
Example: our JSF application will store in an HTTP session only its shopping cart, not the product references
====

==== Error handling

[TIP]
====
How do we deal with errors? Examples of points to be addressed:

* Do we differentiate functional errors (expected functional errors) and technical? Provide a class diagram.
* How do we log errors? what level of log?
* Where are the exceptions caught? at the earliest ou at the start of a call centrally?
* Are we using the language's standard exceptions (`IOException`, ...) or our own set of exceptions?
* Is the list of errors consolidated? documented?
* Are error codes assigned?
* Do we display full stack-traces? if so, server side and client side?
* Do we manage replay? if so, do we space the replay?
* How do we manage timeouts?

====
====
Example (Spring):

(unforeseen) technical errors such as the timeout to a REST service call are caught at the highest level of the application (via an ErrorHandler). All of its information is logged with the full stack-trace but the caller must only retrieve the generic error code XYZ without the stack-trace (for security reasons).
====

=== Configuration management

[TIP]
====
How do you configure the application? Examples of points to be addressed:

* What are the variables included in the final package statically?
* What parameters can be changed at runtime?
* Can my application be configured via feature flags for canary testing reasons for example? if so, how do i handle it in code?
* In what form are the parameters injected into the application (environment variable? .Properties file, database, ...)?
* Does the application accept a modification of the hot configuration?
* Describe the configuration system

====
====
Example (application deployed in Kubernetes):

The configuration will be injected at launch (not hot modifiable) via environment variables provided in the Kubernetes Deployment Descriptor.
====

=== Branch management policy

[TIP]
====
What are the branch workflows to plan? git-flow? TBD (Trunked-based Development)? other?
====

====
Example:

* The general policy adopted is the https://trunkbaseddevelopment.com/inéaTBD] (Trunk-Based Development)
* The main branch is `develop`. This is a protected branch to which commits cannot be pushed.
* Any commit will have to be the object of a Merge Request before integration in `develop`. The quality criteria (automatically evaluated during continuous integration) must be met for the commit to be integrated.
* Each feature, significant refactoring or bugfix will therefore be carried out on a dedicated topic branch.
* A maintenance branch will be pulled on each x.y version tag. Only bugfixes will be merged into maintenance branches from `develop` via` cherry-pick`.
====


=== Versioning

[TIP]
====
What do you version and what version system do you use?
====

====
Example:

* In general, any non-derived resource (source, tool, ci-cd script, template, database DDL, ...) must be versioned.
* The modules will be versioned according to the numbering `x.y.z` (` <major). <Evolution>. <fix> `)
* The libraries will be versioned according to the same numbering as the modules but the `x` value will be incremented during any version upgrade breaking upward compatibility (principle of Semantic Versioning).
* The overall logical version of the project will be: `<lot>. <No sprint>. <Deployment>`

====

=== Competition management

[TIP]
====
How do we manage concurrent access? Examples of points to be addressed:

* What scope for the objects (if using an IoC engine)?
* Should objects be stateless?
* Which methods should be synchronized?
* Risks of race condition? of starvation? dead locks?

====
====
Example (Spring MVC): All controllers will be in singleton scope and therefore must in no case store state in their attributes to avoid race conditions.
====

=== Encoding

[TIP]
====
What are the rules for encoding strings? This is a recurring problem in SI (who has never observed corrupted accents in the form of squares?). This problem is, however, relatively simple to solve and requires only rigor. See the examples below for examples of actual devices.
====

====
Example 1: The only encoding allowed in all modules and technical components is UTF-8. The use of ISO-8859-1, CP-1252 or any other encoding is strictly prohibited. This includes the configuration of application servers (Node, Tomcat ...), sources, databases and files.

Even `.properties` read in Java should be written in UTF-8. You must then specify the encoding during parsing:

`` ``
FileInputStream input = new FileInputStream (new File ("myfile.properties"));
props.load (new InputStreamReader (input, Charset.forName ("UTF-8")));
`` ``

NOTE: In some cases, we do not have control over reading the .properties (from a framework for example), so it is not possible to force an encoding in UTF-8.

====
====
Example 2: If an external system requires sending orto receive character strings in an encoding other than UTF-8 (example: a REST service which returns data in ISO-8859-1) and that it is not possible to modify the contract, it is imperative to translate character strings within an anti-corruption layer as early as possible, from the call. In addition, we must never persist in our systems a data in a non-UTF-8 encoding.
====
 
=== Time zones

[TIP]
====
How do we manage the storage of dates? This, as the management of encoding is a recurring problem (one day shift, bugs during summer / winter time changes, etc.) and yet simple to solve: follow the https: // standard. .wikipedia.org / wiki / ISO_8601[ISO 8601] ("Time zones in ISO 8601 are represented as local time (with the location unspecified), as UTC, or as an offset from UTC."[Wikipedia]).
====

====
Example 1: Hours will never be stored without a time zone. Basically, we will use timestamps with timezone (`timestamptz`) and in Java or JS, objects integrating the time zone explicitly (eg:` Instant` and not `LocalDateTime` in java) or epochs. The precision will be at least a millisecond.
====
====
Example 2: Dates and date-times will be stored in database as epoch millis in long integer format. In the case of dates, we will store the epoch millis at 12:00 UTC (and not 00:00, too close to the previous day, risk of bug).
====

=== Log management

NOTE: The log infrastructure aspects are detailed in link:./pane-architecture-infrastructure.adoc # _logs[the infrastructure pane].

[TIP]
====
Give here the general rules concerning the application traces (logs), the levels and quantity of logs.
Think about the use of logs, especially on the server side. Ask yourself if it will be possible to benefit from it in the event of an error in production in the middle of Mio or even GiB of other logs and n threads logging in parallel.
====

==== General rules

====
Example 1:

* Do not leave development logs in the code (example: `console.out (" entry in method x ")` or `e.printStackTrace ()`)
* Remember to use discriminating character strings (example: error code) to facilitate filtering in the log search tool.
* Always provide entity identifiers allowing to find the concerned object
* Use correlation identifier between third parties (example: processing id generated on the client side in JS, passed to the server)
* Avoid expensive calculations (example: many concatenations) and use conditional blocks (example in Java:
`` java
if (isDebugEnabled ()) {
   logger.debug (a + b + c)
}
`` ``
====

==== Levels and quantity of logs
[TIP]
====
Explain when and what to log in so as to produce logs that can be used in production.
====

====
Example:

.Log levels
[cols = '1,3,1,1']
|====
| Severity level | Context of use | Indicative volume | Surround

| DEBUG
| In a development environment, it allows you to display the values ​​of variables, method I / O, etc.
| Max a few Mio / minute
| DEV, Recipe. Prohibited in PROD unless expressly requested by the project

| INFO
| Start / end of a batch or a call, loading of a new property. Can be used in condensed form for service calls (logging of a call and its context). This is the level of verbosity used for metrology.
| Max 10 logs / sec, a few KiB / minute
| All

| WARN
| All warning messages about unexpected functional information
| No limits but do not abuse them and position as much contextual detail as possible
| All

| ERROR
| All errors that do not prevent the application from working.
| No limits. Position a maximum of context detail
| All

| FATAL
| All blocking errors for the application (BDD access problem, HTTP 404 or 500). Position a maximum of context detail. Remember to log these errors on an appender console in the event that writing to FS is impossible (disk full). Remember that during a fatal error, even writing the log is questionable (for example in the event of memory overflow).
| No limits.
| All
|====

====
 
=== Administrative tools

[TIP]
====
Should the app provide administration services? It is strongly recommended (this is the factor 12 of the Heroku https://12factor.net/ouvernTwelve factors]) to integrate the administration code directly with the business code.

Examples of points to be addressed:

* Do I have to provide a way to purge data, logs, caches, ...?
(this type of service is sometimes called an 'internal processing')
* Do I have to provide application indicators for supervision? (number of files consulted, ...)?
* Do I have to provide migration tools?

====
====
Example: The `/ internal / maj_2` service will perform a version upgrade of the data model to V2
====

=== Sorting and Pagination

[TIP]
====
It is necessary to keepgood fluidity of batch data recovery. The pagination allows to limit the chatter between the clients (GUI and batches) and the APIs. Describe here the paging devices implemented on the client side and on the server side.
====

====
Example 1 (Server side)

* API output requests are systematically sorted in ascending order (the default) or descending order. In addition, it will be possible to choose the field on which the sorting is done via another query param.
* In order to limit the number of requests to the API, it returns a limited number of elements (this number can be configured according to the size of the individual elements). This is the query param `range` containing the number of the page to retrieve + the number of elements of the page. Each API will offer a default value (around a hundred).
====

====
Example 2 (Customer side)

* The sort must be applied to all the elements in the database, not only to the elements of the last query returned by the server.
* The returned elements will be displayed in block tables (configurable size of an indicative size of around 20 elements).
====

=== Provisionning and data updates

[TIP]
====
Describe how the DDL (structures of tables in database) and the initial data (such as nomenclatures) will be managed and then updated.
====

====
Example: We will use LiquiBase embedded in the war to create and update the DDL of the database. There will therefore be no SQL scripts to launch, the necessary queries will be carried out directly by the application when it starts.
====
