@startuml
!include detailled-application-design-static.puml
title detailed-application-architecture-dynamic
header Container diagram \nDynamic detailed application point of view \n My Online Info Project (AllMyData)

Rel(company, static_resources, "Visit https://allmydata.gouv", "HTTPS, synchronous, read only")
Rel(company, spa, "Retrieves information via")
Rel(company, mobile, "Retrieves information via")
Rel(static_resources, spa, "Provide to client's web browser", "HTTPS, synchronous, read-only")
Rel(spa, sm, "[1.1] Info request", "HTTPS, synchronous, read only")
Rel(mobile, sm, "[1.1] Information request", "HTTPS, synchronous, read only")
Rel(sm, bdd, "[1.2] Historization of the request", "JDBC, synchronous, write")
Rel(sm, queue, "[1.3] Request storage", "JMS, synchronous, write")
Rel(batch, queue, "[2.1] Pop requests", "JMS, asynchronous, read then delete")
Rel(batch, scompta, "[2.2] Retrieving accounting information", "HTTPS, synchronous, read only")
Rel(batch, compo, "[2.3] PDF creation", "HTTP, synchronous, read")
Rel(batch, smails, "[2.4] Request to send mail with PDF", "SMTP, synchronous, execution")
Rel(smails, company, "[2.5] Sending mail with PDF", "SMTP, synchronous, execution")

@enduml