@startuml detailed-application-architecture-dynamic
!include detailled-application-design-inventory.puml
header Dynamic detailed application view\n R: Read, W:Write, X: Execute, D: Delete\n Dashed lines: asynchronous call
LAYOUT_WITH_LEGEND()

AddRelTag("async", $lineStyle = DashedLine())

Rel(company, static_resources, "Visit https://allmydata.gouv", "HTTPS, R")
Rel(company, spa, "[1] Retrieves information via")
Rel(company, mobile, "[1] Retrieves information via")
Rel(static_resources, spa, "Provide to client's web browser", "HTTPS, R")
Rel(spa, sm, "[1.1] Info request", "HTTPS,  R")
Rel(mobile, sm, "[1.1] Information request", "HTTPS, R")
Rel(sm, bdd, "[1.2] Historization of the request", "JDBC, W")
Rel(sm, queue, "[1.3] Request storage", "JMS, W",$tags='async')
Rel(batch, queue, "[2.1] Pop requests", "JMS, R+D")
Rel(batch, scompta, "[2.2] Retrieving accounting information", "HTTPS, R")
Rel(batch, compo, "[2.3] PDF creation", "HTTP R")
Rel(batch, smails, "[2.4] Request to send mail with PDF", "SMTP, X")
Rel(smails, smails, "[2.5] Sending mail with PDF", "SMTP, X")

@enduml