@startuml infrastructure
!include <C4/C4_Deployment>
header Infrastucture architecture view
LAYOUT_WITH_LEGEND()

AddElementTag("passive", $bgColor="grey")
AddElementTag("external", $bgColor="grey")

Node("client", "Client", "Desktop / mobile") {
  Node("nav1", "Web browser", "Chrome / Firefox / Safari") {
    Container("spa", "AllMyData SPA application", "React.js")
  }
}

Node("dc", "Datacenter", "Atlanta") {
    Node("r2", "Firewall", "Cisco Firepower 4100")
    Node("lb1", "LB Debian lb1", "<<active>>")
    Node("lb2", "LB Debian lb2", "<<passive>>",$tags="passive")

    Node("rp1", "Reverse Proxy", "x2 Debian Buster <<active/active>>") {
      Container("ha1", "Reverse Proxy", "HaProxy")
    }

    Node("server_gui", "AllMyData server", "x2 Debian Buster") {
      Node("sw1", "Web server", "Nginx") {
        Container("guis1", "SPA Web Application", "React.js", "Expose static resources \n (.js, .html, images ...)")
      }
      Node("tomcat_batchs1", "JEE Server", "Tomcat 10") {
        Container("batch1", "batch-process-requests", "Java", "Process requests")
      }
    }

    Node("API_server", "API Server", "x3, RHEL") {
      Node("wilfly1", "JEE Server", "Wildfly") {
        Container("api1", "API service-allmydata", "Java")
      }
    }

    Node("bdd1", "BDD Server", "RHEL") {
      ContainerDb("pg1", "PostgreSQL", "PostgreSQL 12")
      ContainerDb("mq1", "Message queue", "ActiveMQ")
      Container("mail1", "MTA", "Postfix")
    }

    Node("all_servers","<Any server>")
    Node("sup1_server", "Monitoring Server", "x1 Debian Stretch") {
      Container("sup1", "Monitoring tool", "Centreon")
    }

}

Node("administration_b","Datacenter","NYC",$tags="external"){
     Node("ech1","API Geatexway","x1 Windows Server") {
      Container("gw1","API Gateway","API Gateway")    
    } 

    Node("compta","Accounting Serveur","x1 Linux") {
      Container("api_b","Accounting Service API","")    
    } 
}

Rel("spa", "r2","HTTPS on the Internet")
Rel("r2","lb1","HTTPS")
Rel("lb2", "lb1","Heartbeat VRRP")
Rel("lb1","ha1","")
Rel("ha1","guis1", "HTTP")
Rel("api1", "mq1", "products \n AMQP"))
Rel("batch1","mq1", "consumes \n AMQP")
Rel("api1", "pg1", "JDBC / PG")
Rel("batch1", "mail1", "SMTP / sends e-mails")
Rel("api1","gw1","SOAP/HTTPS")
Rel("gw1","api_b","SOAP/HTTPS")
Rel("ha1","api1","REST/HTTP")
Rel_L("sup1_server","all_servers","SNMP")

@enduml